theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "pacman"

[[block]]
device = "/sys/class/power_supply/BAT1"
block = "battery"
format = "{percentage}%: {time} ({power}W)"

[[block]]
device = "/sys/class/power_supply/BAT0"
block = "battery"
format = "{percentage}%: {time} ({power}W)"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
info = 99
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = false
speed_down = false
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a, %d-%m-%y %H:%M"

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 1
