theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "pacman"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
info = 99
interval = 1

[[block]]
block = "nvidia_gpu"
label = "RTX 2080"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "net"
device = "enp0s31f6"
ssid = true
ip = true
speed_up = false
speed_down = false
interval = 1

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "time"
interval = 60
format = "%a, %d-%m-%y %H:%M"
